babel.config.js
package.json
src/common/Legends/Legends.tsx
src/common/Legends/styles/legends.less
src/components/funnel/demos/drilldown-card.less
src/components/hooks/useOffset.ts
test.json
tsconfig.json
yarn.lock

feat: update configuration for jest and father-build

---

src/common/InfoCard/InfoCard.tsx
src/common/InfoCard/InfoCardBox.tsx
src/common/InfoCard/Item.tsx

fix(InfoCard): fix default valueKey

---

src/common/InfoCard/InfoCard.tsx
src/common/InfoCard/Item.tsx
src/components/line/demos/Line.stories.tsx

feat(InfoCard): add tooltip value formatter

---

src/area/demos/Area.stories.tsx
src/info-card/InfoCardBox.tsx
src/legends/styles/legends.less
src/line/__test__/Line.test.tsx
src/line/__test__/framework.test.tsx
src/line/demos/Line.mdx
src/line/demos/Line.stories.tsx
src/line/demos/data.ts
src/utils/dateFormatter.ts

feat(line storybook): Update storybook for line chart

---

src/core/core.tsx
src/funnel/framework.ts

fix(tooltip): fix there is an error when quick mouseover the chart at first render

---

src/funnel/Funnel.tsx
src/funnel/demos/Funnel.stories.tsx
src/funnel/demos/data.ts
src/funnel/utils.ts

feat(funnel): support contrast in config.funnel

---

src/area/Area.tsx
src/assets/svg/NoDataSvg.tsx
src/boundary/ErrorBoundary.tsx
src/boundary/NoData.tsx
src/boundary/__test__/ErrorBoundary.test.tsx
src/boundary/__test__/NoData.test.tsx
src/boundary/demos/ErrorBoundary.mdx
src/boundary/demos/ErrorBoundary.stories.tsx
src/boundary/demos/NoData.mdx
src/boundary/demos/NoData.stories.tsx
src/boundary/fetchChart.tsx
src/boundary/index.ts
src/boundary/style/NoData.less
src/funnel/__test__/utils.test.ts
src/funnel/demos/data.ts
src/interfaces.ts
src/utils/__test__/formatNumber.test.ts
src/utils/tools/__test__/configUtils.test.ts

Default No Data:
Custom No Data: 
Default Error Boundary
Custom Error Boundary

feat(ErrorBoundary & NoData): support ErrorBoundary and NoData

---

src/boundary/Loading/Loading.tsx
src/boundary/Loading/__test__/Loading.test.tsx
src/boundary/Loading/demos/Loading.mdx
src/boundary/Loading/demos/Loading.stories.tsx
src/boundary/Loading/index.tsx
src/boundary/Loading/style/Loading.less
src/boundary/fetchChart.tsx
src/hooks/useOffset.ts

feat(Loading): support loading for chart

---

src/info-card/styles/infocard.less

fix(InfoCard): fix the max-height of info-card to 300px

---

src/theme/chart.ts

fix(Tooltip): change the color of tooltip crosshairs to gray-3 #ebedf5

---

src/area/framework.ts
src/column/framework.ts
src/core/core.tsx
src/core/framework.ts
src/funnel/framework.ts
src/line/framework.ts
src/utils/tools/__test__/shapeState.test.ts
src/utils/tools/shapeState.ts

feat(Highlight): support highlight for Area

---

package.json
src/core/core.tsx
src/hooks/useTunnel.ts
src/info-card/InfoCardBox.tsx
src/info-card/__test__/InfoCard.test.tsx
src/info-card/__test__/InfoCardBox.test.tsx
yarn.lock

feat(tooltip): useTunnel to update tooltip trigger items to reduce updates in core

---

src/funnel/demos/data.ts
src/theme/chart.ts
src/theme/index.ts
src/utils/tools/intervalLabel.ts

fix(label): update the label color

---

src/utils/tools/intervalLabel.ts

fix(Label): set label offset

---

src/layouts/legend/LegendLayout.tsx
src/layouts/scroll/ScrollXLayout.tsx

fix(ScrollX): reset width in small changes

---

src/core/demos/theme.stories.tsx
src/core/framework.ts
src/hooks/useChart.ts
src/interfaces.ts
src/layouts/legend/LegendLayout.tsx
src/legends/Legend.tsx
src/legends/Legends.tsx
src/theme/chart.ts
src/utils/chart.ts

feat(theme): support custom theme by using chart config 

---

src/hooks/useInterceptors.ts

fix(tooltip): the trigger state should be changed to mouseover

---

CHANGELOG.md
VERSION.md
package.json
src/hooks/useLegends.ts
src/legends/Legend.tsx
src/legends/Legends.tsx

- fix the issue that the label of xAxis is cut by canvas in Safari browser;
- fix the issue that the order of legends is wrong;
- fix the issue that the offsetWidth in legends should exist in first render which causes the count of legends can display
- fix the issue that the tooltip trigger should be changed when mouseout the column

docs(release): release version to 1.0.0-beta.7

---

src/core/framework.ts
src/donut/Donut.tsx
src/donut/__test__/Donut.test.tsx
src/donut/demos/Donut.stories.tsx
src/donut/demos/data.ts
src/donut/framework.ts
src/donut/index.ts
src/funnel/framework.ts
src/hooks/useChart.ts
src/interfaces.ts
src/layouts/legend/LegendLayout.tsx
src/legends/Legends.tsx
src/theme/chart.ts
src/utils/tools/configUtils.ts
src/utils/tools/index.ts
src/utils/tools/sliceShape.ts

feat(Donut): add donut chart

---

CHANGELOG.md
VERSION.md
package.json

* 添加环形图 Donut
* 设置config.chart.height包含Legend高度
* 修改TinyArea的样式问题
* 修改Drag Bar菜单对齐的问题

docs(release): release version to 1.0.0-beta.8

---

CHANGELOG.md
VERSION.md
package.json
src/utils/frameworks/geometry.ts

Features:
* 添加气泡图
* 添加对比折线图，对比不同时间段的数据对比

docs(release): release version to 1.0.0-beta.9

---

CHANGELOG.md
VERSION.md
package.json

docs(release): release version to 1.0.0-beta.12

---

src/core/framework.ts
src/donut/demos/Donut.stories.tsx
src/donut/framework.ts
src/hooks/__test__/useLegends.test.tsx
src/index.ts
src/interfaces.ts
src/line/__test__/framework.test.tsx
src/utils/frameworks/coordinate.ts

Click the legend will do:
* the total count will be changed.
* the percent label for each label will changed

feat(Donut): donut chart improve

---

src/bar/TimeIntervalBar.tsx
src/bar/__test__/Bar.test.tsx
src/bar/demos/TimeIntervalBar.stories.tsx
src/bar/demos/data.ts
src/bar/framework.ts
src/column/framework.ts
src/gauge/framework.ts
src/layouts/legend/LegendLayout.tsx
src/layouts/scroll/ScrollYLayout.tsx
src/theme/index.ts
src/utils/calculate.ts
src/utils/frameworks/coordinate.ts
src/utils/tools/intervalLabel.ts
src/utils/tools/intervalShape.ts
src/utils/tools/shapeState.ts
src/utils/tools/utils.ts

feat(TimeIntervalBar): Add TimeIntervalBar

---

src/line/framework.ts

fix(axis): render wrong label issue

---

CHANGELOG.md
VERSION.md
package.json
src/layouts/scroll/styles/index.less
src/style/scrollBar.less

feat(ScrollBar): support new scroll bar styles

---

src/core/framework.ts

fix(LimitINPlot): the line can't be cut

---

src/donut/framework.ts

fix(Donut): change render function to ignore wrong label

---

src/info-card/styles/infocard.less

fix(InfoCard): the value will show in two lines

---

src/core/framework.ts
src/theme/index.ts
src/tiny-area/demos/TinyArea.stories.tsx

fix(TinyArea): show full boundary line

---

src/core/styles/base.less
src/info-card/InfoCard.tsx
src/info-card/styles/infocard.less
src/layouts/drag/DragLayout.tsx
src/layouts/legend/LegendLayout.tsx

Co-authored-by: Zhang Rui <zhangrui@growingio.com>

fix(Title): update title style (#251)

---

src/funnel/__test__/utils.test.ts
src/funnel/framework.ts
src/funnel/utils.ts
src/utils/tools/elementLink.ts
src/utils/tools/interfaces.ts

fix(Funnel): control arrow count in funnel

---

src/line/demos/Line.stories.tsx
src/line/demos/data.ts
src/line/framework.ts

fix(ContrastLine): fix the issue of the compare lengths are different

---

src/area/framework.ts
src/double-axes/DoubleAxes.tsx
src/double-axes/demos/DoubleAxes.stories.tsx
src/double-axes/demos/data.ts
src/double-axes/framework.ts
src/double-axes/index.tsx
src/hooks/useChart.ts
src/interfaces.ts
src/legends/useLegends.ts
src/line/framework.ts
yarn.lock

在配置上需要注意3点：
1. legend图例上显示横线，需要在legend的配置上添加`type: "line"`；
2. 去除line图相关的分割线和label，需要配置`axis`
`axises: [["lineValue": {grid: null, label: "null"}]]`
3. 折线的配置，需要添加`line配置`，柱状图的配置需要用到`column配置`；

feat(DoubleAxes): 支持双轴图表

---

src/boundary/fetchChart.tsx

fix: 修改翻译(2)

---

src/funnel/demos/Funnel.stories.tsx
src/funnel/demos/data.ts
src/funnel/utils.ts

fix(Funnel): 增加留存图的间距
